//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workshop.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presenter
    {
        public int PresenterId { get; set; }
        public string PresenterName { get; set; }
    
        public virtual Workshop Workshop { get; set; }
    }
}
