//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workshop
    {
        public int WorkshopId { get; set; }
        public string WorkshopName { get; set; }
        public string WorkshopDescription { get; set; }
        public Nullable<System.DateTime> WorkshopDate { get; set; }
        public Nullable<int> PresenterId { get; set; }
    
        public virtual Presenter Presenter { get; set; }
    }
}
